# Generated by Django 4.2.1 on 2023-06-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_alter_registerstudent_studentimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerstudent',
            old_name='password',
            new_name='studentpassword',
        ),
    ]
