# Generated by Django 4.2.1 on 2023-06-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_rename_password_registerstudent_studentpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
